// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUscdSh0E13Tn7KynLcCzX-yrKoZiQvxU',
    appId: '1:839868664740:web:1988fffc571fd5b066cf31',
    messagingSenderId: '839868664740',
    projectId: 'vascoapp-9adec',
    authDomain: 'vascoapp-9adec.firebaseapp.com',
    storageBucket: 'vascoapp-9adec.firebasestorage.app',
    measurementId: 'G-EE1WYG4K8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQjPytRYO1g_Kwm0pw8cLIf_2jsOmRUo',
    appId: '1:839868664740:android:3b5b4f6c6ab405f166cf31',
    messagingSenderId: '839868664740',
    projectId: 'vascoapp-9adec',
    storageBucket: 'vascoapp-9adec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzMljMJpAnIIh_El4iWGM5OyOdsOtRYE',
    appId: '1:839868664740:ios:668a40f98e29da8966cf31',
    messagingSenderId: '839868664740',
    projectId: 'vascoapp-9adec',
    storageBucket: 'vascoapp-9adec.firebasestorage.app',
    androidClientId:
        '839868664740-khlrrk6rpu0bhqaov8bnv5bbmvh3eo3g.apps.googleusercontent.com',
    iosClientId:
        '839868664740-amg9m7t7jfeiir9f9auov8o2594etjj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.vasco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuzMljMJpAnIIh_El4iWGM5OyOdsOtRYE',
    appId: '1:839868664740:ios:668a40f98e29da8966cf31',
    messagingSenderId: '839868664740',
    projectId: 'vascoapp-9adec',
    storageBucket: 'vascoapp-9adec.firebasestorage.app',
    androidClientId:
        '839868664740-khlrrk6rpu0bhqaov8bnv5bbmvh3eo3g.apps.googleusercontent.com',
    iosClientId:
        '839868664740-amg9m7t7jfeiir9f9auov8o2594etjj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.vasco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUscdSh0E13Tn7KynLcCzX-yrKoZiQvxU',
    appId: '1:839868664740:web:d9cb3a764f6d089566cf31',
    messagingSenderId: '839868664740',
    projectId: 'vascoapp-9adec',
    authDomain: 'vascoapp-9adec.firebaseapp.com',
    storageBucket: 'vascoapp-9adec.firebasestorage.app',
    measurementId: 'G-VH17GQTTGN',
  );
}
